export { default as Checkmark } from "./checkmark.svg";
export { default as ChevronRt } from "./chevron-right.svg";
export { default as Location } from "./location.svg";
export { default as Menu } from "./menu.svg";
export { default as Nav } from "./nav.svg";
export { default as Chat } from "./chat.svg";
export { default as Gift } from "./gift.svg";
export { default as Foot } from "./foot.svg";
export { default as Search } from "./search.svg";
